
version: '3.3'
services:
  sql-server:
    container_name: atm-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=sqlDevops12345#2
      - MSSQL_PID=Developer
    volumes:
      - ./backups:/var/opt/mssql/backups/
